# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55821d19aa2ac333dad3b0766e5b2d6b0c2a8072bf29aacf1b2e09e8330e448285ce45d1f70b4f065c76bb18cb1bf9a309e79f7f686513b8ba93d482c5cdea3

test:
  secret_key_base: 6d16f2d9dc7e81c557c4a42a512b7f11c1407532e301b1ed1b06f48318e3ed27f0c25ff69c04ee1f48e351de3034e345b41f4ecd1b52338c771469494d2f355a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
